### ISSUE TITLE
Init project

### ISSUE THREAD

**Issue by S-Eibl** [Interactions-HSG/pb-td-gen#1]
A Go project should be initialized with the following elements:

- The project should have "pb-td-gen" as module name
- The language standard should be set to the last stable Go version 1.18
- The project should import the package [proto](https://github.com/emicklei/proto)
- A source folder should be present on the base repository providing a Main.go file to start from
- An empty folder for files should be present on the base repository

**Comment by iomz** [comment]
It's great that you list todos an issue, but the reasoning for "should" is missing...
Why they "should" be that way?

Anyway, I think this issue has run its course...
