### ISSUE TITLE
Implement mapping from Json blueprint to maps

### ISSUE THREAD

**Issue by S-Eibl** [Interactions-HSG/pb-td-gen#9]
Issue #7 Unmarshall the json into predefined structs. To be more flexible with handling the json blueprint this issue should target the possibility to convert into maps. The structure of the example blueprint JSON is therefor changed. The same example as in #7 is used exposing the collisionSensitivity. The sample blueprint for map now looks like this:
```
{
  "<rpcFunction.Name>": {
    "title": {
      "value_": "<rpcFunction.Comment.long-title>",
      "required_": true
    },
    "description": {
      "value_":  "<rpcFunction.Comment.description>",
      "recommended_": true
    },
    "type": {
      "value_": "<responseMsg.Name>",
      "required_": true
    },
    "minimum": {
      "value_": "<rpcFunction.Comment.minimum>"
    },
    "maximum": {
      "value_": "<rpcFunction.Comment.maximum>"
    }
  }
}
```
Another benefit is that it is now possible to use fields like "<rpcFunction.Name>" also on the left side of assignments which improves the readability of the structure. 
Fields that are annotated with an underscore as suffix. This should mark fields that will be converted into a struct to have predefined properties for the specific values. This also allows for annotations like "required" or "recommended"

### Tasks
- A struct has to be implemented that defines the available keywords for a field in the blueprint
- A recursive function which processes the tree of maps derived from the json Unmarshall
- A function that Unmarshall the json and calls the recursive function on it

**Comment by iomz** [comment]
I don't understand "Unmarshall the json into predefined structs" and "the json blueprint". We marshal a TD struct by `encoding/json` but not the other way around.
Or, by saying "blueprint" are you trying to use a templating engine like [valyala/quicktemplate](https://github.com/valyala/quicktemplate)?

**Comment by iomz** [comment]
[github.com/linksmart/thing-directory/wot](https://github.com/linksmart/thing-directory/blob/master/wot/thing_description.go) already implements a proper `ThingDescription` type that works well with the JSON marshaller.

Closing.
